name: Run Tests on Push or Pull Request to Main

on:
  push:
    branches:
      - main   # Run tests on any push to the main branch
  pull_request:
    branches:
      - main   # Run tests on any pull request to the main branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"   # ✅ Pin to the version you’re using locally

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Run tests with pytest and enforce 100% coverage
        run: |
          pytest --cov=app --cov-report=term-missing --cov-fail-under=100


